// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqxwJcQCFHU9UpzU_4kjhlUNED4JU57NM',
    appId: '1:454809432003:web:e6c05beab053e820bf9776',
    messagingSenderId: '454809432003',
    projectId: 'hostel-saas-dev',
    authDomain: 'hostel-saas-dev.firebaseapp.com',
    storageBucket: 'hostel-saas-dev.firebasestorage.app',
    measurementId: 'G-FW11T85ZGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJp0VsandCG6wOrD5UKEYOjYjX0lflSQ',
    appId: '1:454809432003:android:8412d2d6f4e7d33dbf9776',
    messagingSenderId: '454809432003',
    projectId: 'hostel-saas-dev',
    storageBucket: 'hostel-saas-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6iP1iGe1sDurDKLiNk4TU_r4Hn3onmA',
    appId: '1:454809432003:ios:09214f929b07e7b9bf9776',
    messagingSenderId: '454809432003',
    projectId: 'hostel-saas-dev',
    storageBucket: 'hostel-saas-dev.firebasestorage.app',
    iosBundleId: 'com.example.hostelSaas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc6iP1iGe1sDurDKLiNk4TU_r4Hn3onmA',
    appId: '1:454809432003:ios:09214f929b07e7b9bf9776',
    messagingSenderId: '454809432003',
    projectId: 'hostel-saas-dev',
    storageBucket: 'hostel-saas-dev.firebasestorage.app',
    iosBundleId: 'com.example.hostelSaas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqxwJcQCFHU9UpzU_4kjhlUNED4JU57NM',
    appId: '1:454809432003:web:3e5c1614ae4e232ebf9776',
    messagingSenderId: '454809432003',
    projectId: 'hostel-saas-dev',
    authDomain: 'hostel-saas-dev.firebaseapp.com',
    storageBucket: 'hostel-saas-dev.firebasestorage.app',
    measurementId: 'G-M2C5CQC8WB',
  );
}
